# Remap prefix from 'C-b' to backticks
# From https://gist.github.com/JikkuJose/7509315
unbind C-b
set-option -g prefix `
bind ` send-prefix

# Split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# Make window and pane index 1-based (0 by default)
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g history-limit 100000

# Set status bar colors
set-option -g status-fg colour75
set-option -g status-bg default
set-option -g status-position top
set-option -g status-interval 1

# Set window/pane colors and add "padding" around panes and windows
setw -g window-style bg=default
setw -g window-active-style bg=default
set -g pane-border-style bg=default,fg=colour240
set -g pane-active-border-style bg=default,fg=colour240
set -g pane-border-style fg=colour240

# Set 256 colour scheme inside Tmux
set-option -g default-terminal "screen-256color"

# Statusbar
set -g status-left ''
set -g status-right '#[fg=colour75] %H:%M:%S'
